In [2]:
import pandas as pd
import random
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.datasets import make_blobs 
%matplotlib inline

In [3]:
l = pd.read_csv('./landslide_mod.csv')
GL = pd.read_csv('./GlobalLandslide_mod.csv')

In [4]:
l.head()

,Unnamed: 0,Date,country,landslide_type,trigger,landslide_size,population,latitude,longitude
0,560,05/30/2008,Italy,Mudslide,Downpour,Medium,16800.0,44.6467,7.6639
1,561,05/30/2008,Italy,Mudslide,Downpour,Medium,809.0,44.8098,7.1526
2,562,05/30/2008,Italy,Mudslide,Downpour,Medium,2982.0,45.7513,7.3760
3,937,12/17/2008,Italy,Mudslide,Downpour,Medium,169140.0,38.1102,15.6508
4,978,01/26/2009,Italy,Mudslide,Downpour,Medium,959470.0,40.8403,14.2520

In [5]:
l.dtypes

Unnamed: 0          int64
Date               object
country            object
landslide_type     object
trigger            object
landslide_size     object
population        float64
latitude          float64
longitude         float64
dtype: object

In [22]:
l['landslide_size'].value_counts()

3    45
2     5
4     4
1     1
Name: landslide_size, dtype: int64

In [10]:
for i in range(len(l)):
    
    if (l['trigger'][i] == "Downpour"):
        l['trigger'][i] = 1
        
    if (l['trigger'][i] == "Rain"):
        l['trigger'][i] = 1    
        
    if (l['trigger'][i] == "Earthquake"):
        l['trigger'][i] = 2
        
    if (l['trigger'][i] == "Continuous_Rain"):
        l['trigger'][i] = 1   
        
    if (l['trigger'][i] == "Unknown"):
        l['trigger'][i] = 0

C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2844945422.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['trigger'][i] = 1
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2844945422.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['trigger'][i] = 1
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2844945422.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['trigger'][i] = 2
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2844945422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['trigger'][i] = 1
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2844945422.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['trigger'][i] = 0

In [20]:
for i in range(len(l)):
    
    if (l['landslide_size'][i] == "Very_large"):
        l['landslide_size'][i] = 1
        
    if (l['landslide_size'][i] == "Large"):
        l['landslide_size'][i] = 2   
        
    if (l['landslide_size'][i] == "Medium"):
        l['landslide_size'][i] = 3
        
    if (l['landslide_size'][i] == "Small"):
        l['landslide_size'][i] = 4

C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2021815583.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['landslide_size'][i] = 3
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2021815583.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['landslide_size'][i] = 2
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2021815583.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['landslide_size'][i] = 4
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/2021815583.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l['landslide_size'][i] = 1

In [ ]:
for i in range(len(l)):
    
    if (l['landslide_type'][i] == "Landslide"):
        l['landslide_type'][i] = 1
        
    if (l['landslide_type'][i] == "Mudslide"):
        l['landslide_type'][i] = 2   
        
    if (l['landslide_type'][i] == "Rockfall"):
        l['landslide_type'][i] = 3

In [21]:
l.head()

,Unnamed: 0,Date,country,landslide_type,trigger,landslide_size,population,latitude,longitude
0,560,05/30/2008,Italy,2,1,3,16800.0,44.6467,7.6639
1,561,05/30/2008,Italy,2,1,3,809.0,44.8098,7.1526
2,562,05/30/2008,Italy,2,1,3,2982.0,45.7513,7.3760
3,937,12/17/2008,Italy,2,1,3,169140.0,38.1102,15.6508
4,978,01/26/2009,Italy,2,1,3,959470.0,40.8403,14.2520

In [23]:
l.to_csv('./landslide_mod2.csv')

In [24]:
GL.head()

,Unnamed: 0,landstyle_type,trigger,landslide_size,country_name,population,longitude,latitude,Date
0,0,mudslide,downpour,medium,Italy,959470,14.2520,40.8403,2009-01-26
1,2,landslide,downpour,medium,Italy,9205,16.6525,40.5452,2013-12-03
2,3,mudslide,downpour,medium,Italy,887,14.6074,40.6378,2010-09-10
3,5,mudslide,downpour,medium,Italy,988,16.1928,39.0177,2011-03-01
4,7,landslide,downpour,small,Italy,1250,16.1580,39.1854,2011-11-23

In [35]:
l['trigger'].value_counts()

1    51
0     3
2     1
Name: trigger, dtype: int64

In [31]:
for i in range(len(GL)):
    
    if (GL['landslide_size'][i] == "very_large"):
        GL['landslide_size'][i] = 1
        
    if (GL['landslide_size'][i] == "large"):
        GL['landslide_size'][i] = 2   
        
    if (GL['landslide_size'][i] == "medium"):
        GL['landslide_size'][i] = 3
        
    if (GL['landslide_size'][i] == "small"):
        GL['landslide_size'][i] = 4

C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/492990382.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GL['landslide_size'][i] = 3
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/492990382.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GL['landslide_size'][i] = 4
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/492990382.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GL['landslide_size'][i] = 2
C:\Users\dasa\AppData\Local\Temp/ipykernel_14144/492990382.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GL['landslide_size'][i] = 1

In [32]:
GL.head()

,Unnamed: 0,landstyle_type,trigger,landslide_size,country_name,population,longitude,latitude,Date
0,0,mudslide,downpour,3,Italy,959470,14.2520,40.8403,2009-01-26
1,2,landslide,downpour,3,Italy,9205,16.6525,40.5452,2013-12-03
2,3,mudslide,downpour,3,Italy,887,14.6074,40.6378,2010-09-10
3,5,mudslide,downpour,3,Italy,988,16.1928,39.0177,2011-03-01
4,7,landslide,downpour,4,Italy,1250,16.1580,39.1854,2011-11-23